In [127]:
import pandas as pd 
import numpy as np

df = pd.read_csv('kaggle_london_house_price_data.csv')
df

# Making a predicitve model using supervised learning

,fullAddress,postcode,country,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,...,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,saleEstimate_valueChange.saleDate,history_date,history_price,history_percentageChange,history_numericChange
0,"Flat 9, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,1.0,1.0,45.0,1.0,...,630000.0,HIGH,2024-10-07T13:26:59.894Z,244000.0,68.539326,2010-03-30,1995-01-02,830000,NaN,NaN
1,"Flat 6, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,NaN,NaN,NaN,NaN,...,660000.0,MEDIUM,2024-10-07T13:26:59.894Z,425000.0,242.857143,2000-05-26,1995-01-02,830000,NaN,NaN
2,"Flat 35, Octavia House, Medway Street, London,...",SW1P 2TA,England,SW1P,51.495505,-0.132379,2.0,2.0,71.0,1.0,...,834000.0,MEDIUM,2025-01-10T11:04:57.114Z,49000.0,6.901408,2019-09-04,1995-01-03,249950,NaN,NaN
3,"24 Chester Court, Lomond Grove, London, SE5 7HS",SE5 7HS,England,SE5,51.478185,-0.092201,1.0,1.0,64.0,1.0,...,407000.0,HIGH,2024-10-07T13:26:59.894Z,28000.0,7.777778,2024-01-25,1995-01-03,32000,NaN,NaN
4,"18 Alexandra Gardens, London, N10 3RL",N10 3RL,England,N10,51.588774,-0.139599,1.0,4.0,137.0,2.0,...,1324000.0,HIGH,2024-10-07T13:26:59.894Z,81000.0,6.864407,2022-12-14,1995-01-03,133000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418196,"9 Harvard Road, London, SE13 6SE",SE13 6SE,England,SE13,51.452919,-0.010221,2.0,3.0,123.0,2.0,...,711000.0,HIGH,2025-01-10T11:04:57.114Z,27000.0,4.153846,2024-09-27,2024-09-27,650000,17.117117,95000.0
418197,"Lower Ground Floor Flat 5, Northwood Hall, Hor...",N6 5PE,England,N6,51.571692,-0.137007,1.0,2.0,60.0,1.0,...,473000.0,HIGH,2025-01-10T11:04:57.114Z,10000.0,2.272727,2024-09-27,2024-09-27,440000,2.325581,10000.0
418198,"17 Merritt Road, London, SE4 1DU",SE4 1DU,England,SE4,51.456054,-0.035073,2.0,3.0,100.0,1.0,...,853000.0,HIGH,2025-01-10T11:04:57.114Z,38000.0,4.909561,2024-09-27,2024-09-27,774000,128.655835,435500.0
418199,"15 Chester Row, London, SW1W 9JF",SW1W 9JF,England,SW1W,51.493587,-0.152122,3.0,4.0,218.0,2.0,...,5975000.0,MEDIUM,2025-01-10T11:04:57.114Z,-818000.0,-13.088000,2024-09-27,2024-09-27,6250000,73.611111,2650000.0
418200,"56 Whiteley Road, London, SE19 1JT",SE19 1JT,England,SE19,51.424412,-0.090256,1.0,5.0,154.0,2.0,...,1031000.0,HIGH,2025-01-10T11:04:57.114Z,55000.0,5.876011,2024-09-27,2024-09-27,927500,692.735043,810500.0

In [129]:
df_1 = df.drop(columns=['outcode', 'saleEstimate_ingestedAt', 'fullAddress', 
                        'postcode', 'country',], axis=1)
df_1.columns

Index(['latitude', 'longitude', 'bathrooms', 'bedrooms', 'floorAreaSqM',
       'livingRooms', 'tenure', 'propertyType', 'currentEnergyRating',
       'rentEstimate_lowerPrice', 'rentEstimate_currentPrice',
       'rentEstimate_upperPrice', 'saleEstimate_lowerPrice',
       'saleEstimate_currentPrice', 'saleEstimate_upperPrice',
       'saleEstimate_confidenceLevel',
       'saleEstimate_valueChange.numericChange',
       'saleEstimate_valueChange.percentageChange',
       'saleEstimate_valueChange.saleDate', 'history_date', 'history_price',
       'history_percentageChange', 'history_numericChange'],
      dtype='object')

In [131]:
df_1.head()

,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,tenure,propertyType,currentEnergyRating,rentEstimate_lowerPrice,...,saleEstimate_currentPrice,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,saleEstimate_valueChange.saleDate,history_date,history_price,history_percentageChange,history_numericChange
0,51.517282,-0.110314,1.0,1.0,45.0,1.0,Leasehold,Purpose Built Flat,NaN,2100.0,...,600000.0,630000.0,HIGH,244000.0,68.539326,2010-03-30,1995-01-02,830000,NaN,NaN
1,51.517282,-0.110314,NaN,NaN,NaN,NaN,Leasehold,Flat/Maisonette,NaN,2100.0,...,600000.0,660000.0,MEDIUM,425000.0,242.857143,2000-05-26,1995-01-02,830000,NaN,NaN
2,51.495505,-0.132379,2.0,2.0,71.0,1.0,Leasehold,Flat/Maisonette,C,2650.0,...,759000.0,834000.0,MEDIUM,49000.0,6.901408,2019-09-04,1995-01-03,249950,NaN,NaN
3,51.478185,-0.092201,1.0,1.0,64.0,1.0,Leasehold,Flat/Maisonette,D,1850.0,...,388000.0,407000.0,HIGH,28000.0,7.777778,2024-01-25,1995-01-03,32000,NaN,NaN
4,51.588774,-0.139599,1.0,4.0,137.0,2.0,Freehold,End Terrace House,D,4350.0,...,1261000.0,1324000.0,HIGH,81000.0,6.864407,2022-12-14,1995-01-03,133000,NaN,NaN

In [133]:
df_2 = df_1.dropna()
df_2.isnull().sum()

latitude                                     0
longitude                                    0
bathrooms                                    0
bedrooms                                     0
floorAreaSqM                                 0
livingRooms                                  0
tenure                                       0
propertyType                                 0
currentEnergyRating                          0
rentEstimate_lowerPrice                      0
rentEstimate_currentPrice                    0
rentEstimate_upperPrice                      0
saleEstimate_lowerPrice                      0
saleEstimate_currentPrice                    0
saleEstimate_upperPrice                      0
saleEstimate_confidenceLevel                 0
saleEstimate_valueChange.numericChange       0
saleEstimate_valueChange.percentageChange    0
saleEstimate_valueChange.saleDate            0
history_date                                 0
history_price                                0
history_percentageChange                     0
history_numericChange                        0
dtype: int64

In [135]:
df_2.duplicated().sum()

210

In [139]:
df_3 = df_2.drop_duplicates()

In [141]:
df_3.duplicated().sum()

0

In [143]:
from sklearn import preprocessing

label_encode = preprocessing.LabelEncoder()

df_3 = df_3.copy()

df_3['saleEstimate_confidenceLevel'] = label_encode.fit_transform(df_3['saleEstimate_confidenceLevel'])

In [159]:
len(df_3)

157061

In [145]:
train_data_1, test_data, val_data_1 = df_3[:140001], df_3[140001:150001], df_3[150001:]

train_data = train_data_1[['saleEstimate_confidenceLevel',  
       'rentEstimate_lowerPrice', 'rentEstimate_currentPrice',
       'rentEstimate_upperPrice', 'saleEstimate_lowerPrice',
       'saleEstimate_currentPrice', 'saleEstimate_upperPrice',
       'saleEstimate_valueChange.numericChange',
       'saleEstimate_valueChange.percentageChange', 'history_price',
       'history_percentageChange', 'history_numericChange']]

val_data = val_data_1[['saleEstimate_confidenceLevel',  
       'rentEstimate_lowerPrice', 'rentEstimate_currentPrice',
       'rentEstimate_upperPrice', 'saleEstimate_lowerPrice',
       'saleEstimate_currentPrice', 'saleEstimate_upperPrice',
       'saleEstimate_valueChange.numericChange',
       'saleEstimate_valueChange.percentageChange', 'history_price',
       'history_percentageChange', 'history_numericChange']]


# Remember to use '[[]]'

In [147]:
train_data

,saleEstimate_confidenceLevel,rentEstimate_lowerPrice,rentEstimate_currentPrice,rentEstimate_upperPrice,saleEstimate_lowerPrice,saleEstimate_currentPrice,saleEstimate_upperPrice,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,history_price,history_percentageChange,history_numericChange
849,0,2500.0,2800.0,3150.0,756000.0,796000.0,836000.0,679000.0,577.446809,81500,16.428571,11500.0
961,0,1700.0,1900.0,2150.0,570000.0,600000.0,630000.0,30000.0,5.263158,65000,44.605117,20050.0
1173,0,1650.0,1800.0,1950.0,446000.0,470000.0,493000.0,50000.0,11.904762,16950,-50.869565,-17550.0
1301,0,2900.0,3150.0,3400.0,649000.0,683000.0,717000.0,-42000.0,-5.793103,46000,142.105263,27000.0
1439,0,3900.0,4350.0,4850.0,1066000.0,1122000.0,1178000.0,37000.0,3.410138,130000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
387599,0,2550.0,2800.0,3050.0,685000.0,721000.0,757000.0,56000.0,8.421053,665000,527.358491,559000.0
387600,0,2350.0,2600.0,2850.0,645000.0,679000.0,713000.0,19000.0,2.878788,660000,29.411765,150000.0
387601,0,3700.0,4050.0,4400.0,884000.0,931000.0,978000.0,53000.0,6.095415,877512,251.004800,627512.0
387603,0,1450.0,1550.0,1700.0,307000.0,323000.0,340000.0,13000.0,4.193548,310000,93.750000,150000.0
387605,2,850.0,900.0,950.0,155000.0,172000.0,189000.0,12000.0,7.500000,160000,100.000000,80000.0

In [149]:
X_train, y_train = train_data.to_numpy()[:, :-1], train_data.to_numpy()[:, -1]
X_val, y_val = val_data.to_numpy()[:, :-1], val_data.to_numpy()[:, -1]
X_train

array([[ 0.00000000e+00,  2.50000000e+03,  2.80000000e+03, ...,
         5.77446809e+02,  8.15000000e+04,  1.64285714e+01],
       [ 0.00000000e+00,  1.70000000e+03,  1.90000000e+03, ...,
         5.26315789e+00,  6.50000000e+04,  4.46051168e+01],
       [ 0.00000000e+00,  1.65000000e+03,  1.80000000e+03, ...,
         1.19047619e+01,  1.69500000e+04, -5.08695652e+01],
       ...,
       [ 0.00000000e+00,  3.70000000e+03,  4.05000000e+03, ...,
         6.09541522e+00,  8.77512000e+05,  2.51004800e+02],
       [ 0.00000000e+00,  1.45000000e+03,  1.55000000e+03, ...,
         4.19354839e+00,  3.10000000e+05,  9.37500000e+01],
       [ 2.00000000e+00,  8.50000000e+02,  9.00000000e+02, ...,
         7.50000000e+00,  1.60000000e+05,  1.00000000e+02]])

In [151]:
X_train.shape

(140001, 11)

In [153]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train[:, 3:])

def pre_pro(X):
    a = np.copy(X)
    a[:, 3:] = scaler.transform(a[:, 3:])
    return a


X_train_process = pre_pro(X_train)
X_train_process

X_val_process = pre_pro(X_val)
X_val_process

array([[ 0.00000000e+00,  2.10000000e+03,  2.35000000e+03, ...,
        -2.93929852e-02, -1.28015587e-01, -3.37790362e-01],
       [ 0.00000000e+00,  3.95000000e+03,  4.50000000e+03, ...,
        -6.80106063e-02,  8.24426714e-01, -1.49613873e-01],
       [ 0.00000000e+00,  1.90000000e+03,  2.10000000e+03, ...,
        -5.55415958e-02, -7.27124852e-02,  8.78719832e-02],
       ...,
       [ 0.00000000e+00,  3.10000000e+03,  3.45000000e+03, ...,
        -4.99352333e-02,  1.84139697e-01,  7.23334462e-02],
       [ 2.00000000e+00,  1.90500000e+04,  2.09000000e+04, ...,
        -1.15170229e-01,  6.91391265e+00, -1.05293112e-01],
       [ 0.00000000e+00,  3.55000000e+03,  3.90000000e+03, ...,
        -4.64321827e-02,  3.72784720e-01,  1.89258872e+00]])

In [155]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.linear_model import LinearRegression

lr = LinearRegression().fit(X_train_process, y_train)
rse = mse(lr.predict(X_train_process), y_train, squared=False)
rse_val = mse(lr.predict(X_val_process), y_val, squared=False)
rse, rse_val
# RMSE measures how well the model fits the training data
# A lower RMSE value means the model’s predictions are closer to the actual values, indicating better accuracy
# rse_val measures how well the model generalises to unseen validation data
# If rse_val is much larger than rse, it might suggest the model is overfitting the training data.

(313677.6537254166, 275187.1056037018)

In [157]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(max_depth=3).fit(X_train_process, y_train)

rse = mse(rf.predict(X_train_process), y_train, squared=False)
rse_val = mse(rf.predict(X_val_process), y_val, squared=False)
rse, rse_val

(251624.78588428735, 200530.81809072927)

In [13]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=2).fit(X_train_process, y_train)

rse = mse(knn.predict(X_train_process), y_train, squared=False)
rse_val = mse(knn.predict(X_val_process), y_val, squared=False)
rse, rse_val

# KNN 'n_neighbors=' cannot be 1

(267915.3608472997, 290750.27227538364)

In [14]:
from sklearn.ensemble import GradientBoostingRegressor

gb = GradientBoostingRegressor(n_estimators=50).fit(X_train_process, y_train)

rse = mse(gb.predict(X_train_process), y_train, squared=False)
rse_val = mse(gb.predict(X_val_process), y_val, squared=False)
rse, rse_val

(83245.16760100253, 51076.26143671453)

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam

simple_ann = Sequential()
# Defining the layers
simple_ann.add(Input((11,))) # dataset has 11 features to input
simple_ann.add(Dense(2, 'relu'))
simple_ann.add(Dense(1, 'linear'))

opt = Adam(learning_rate=0.1)
cp = ModelCheckpoint('models/simple_ann.keras', save_best_only=True)
simple_ann.compile(optimizer=opt, loss='mse', metrics=[RootMeanSquaredError()])
simple_ann.fit(x=X_train_process, y=y_train, validation_data=(X_val_process, y_val), callbacks=[cp], epochs=10)

# loss: the Mean Squared Error (MSE) (loss='mse' setting)
# Measures the average squared difference between your model’s predicted values and the true target values. Lower values indicate better fit.

# root_mean_squared_error: measures the average prediction error in the original units of the target variable
# Lower values mean the predictions are closer to the actual values on average

# val_loss: This is the loss (MSE) calculated on the validation data
# Evaluates how well the model generalises to new data

# val_root_mean_squared_error: This is the RMSE calculated on the validation data
# Also, shows the typical prediction error on unseen data.

Epoch 1/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 373173452800.0000 - root_mean_squared_error: 610879.2500 - val_loss: 224807960576.0000 - val_root_mean_squared_error: 474139.1875
Epoch 2/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - loss: 372973010944.0000 - root_mean_squared_error: 610715.1875 - val_loss: 224617283584.0000 - val_root_mean_squared_error: 473938.0625
Epoch 3/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 372773060608.0000 - root_mean_squared_error: 610551.4375 - val_loss: 224427065344.0000 - val_root_mean_squared_error: 473737.3438
Epoch 4/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 372575698944.0000 - root_mean_squared_error: 610389.8125 - val_loss: 224237666304.0000 - val_root_mean_squared_error: 473537.4062
Epoch 5/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 372376633344.0000 - root_mean_squared_error: 610226.6875 - val_loss: 224048005120.0000 - val_root_mean_squared_error: 473337.0938
Epoch 6/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - loss: 372179533824.0000 - root_mean_squared_error: 610065.1875 - val_loss: 223859933184.0000 - val_root_mean_squared_error: 473138.3750
Epoch 7/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 29s 7ms/step - loss: 371982041088.0000 - root_mean_squared_error: 609903.3125 - val_loss: 223671549952.0000 - val_root_mean_squared_error: 472939.2812
Epoch 8/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - loss: 371785007104.0000 - root_mean_squared_error: 609741.7500 - val_loss: 223483592704.0000 - val_root_mean_squared_error: 472740.5000
Epoch 9/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 371587088384.0000 - root_mean_squared_error: 609579.4375 - val_loss: 223294521344.0000 - val_root_mean_squared_error: 472540.5000
Epoch 10/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - loss: 371390906368.0000 - root_mean_squared_error: 609418.5000 - val_loss: 223107547136.0000 - val_root_mean_squared_error: 472342.6250
Epoch 11/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 371193577472.0000 - root_mean_squared_error: 609256.5625 - val_loss: 222919688192.0000 - val_root_mean_squared_error: 472143.7188
Epoch 12/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 371001425920.0000 - root_mean_squared_error: 609098.8750 - val_loss: 222737219584.0000 - val_root_mean_squared_error: 471950.4375
Epoch 13/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 370807046144.0000 - root_mean_squared_error: 608939.2500 - val_loss: 222551769088.0000 - val_root_mean_squared_error: 471753.9375
Epoch 14/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 370612142080.0000 - root_mean_squared_error: 608779.2500 - val_loss: 222365286400.0000 - val_root_mean_squared_error: 471556.2500
Epoch 15/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - loss: 370417991680.0000 - root_mean_squared_error: 608619.7500 - val_loss: 222180360192.0000 - val_root_mean_squared_error: 471360.1250
Epoch 16/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 370224300032.0000 - root_mean_squared_error: 608460.6250 - val_loss: 221995139072.0000 - val_root_mean_squared_error: 471163.5938
Epoch 17/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 370030477312.0000 - root_mean_squared_error: 608301.3125 - val_loss: 221810900992.0000 - val_root_mean_squared_error: 470968.0312
Epoch 18/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 18s 4ms/step - loss: 369837408256.0000 - root_mean_squared_error: 608142.5625 - val_loss: 221626023936.0000 - val_root_mean_squared_error: 470771.7188
Epoch 19/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 369643257856.0000 - root_mean_squared_error: 607982.9375 - val_loss: 221441294336.0000 - val_root_mean_squared_error: 470575.5000
Epoch 20/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - loss: 369450090496.0000 - root_mean_squared_error: 607824.0625 - val_loss: 221257629696.0000 - val_root_mean_squared_error: 470380.3125

In [33]:
from tensorflow.keras.models import load_model

simple_ann = load_model('models/simple_ann.keras')
mse(simple_ann.predict(X_train_process), y_train, squared=False), mse(simple_ann.predict(X_val_process), y_val, squared=False)

4376/4376 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step
228/228 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

(607745.0399278367, 470380.3219740291)

In [35]:
compl_ann = Sequential()
compl_ann.add(Input((11,))) # dataset has 11 features to input
compl_ann.add(Dense(32, 'relu'))
compl_ann.add(Dense(16, 'relu'))
compl_ann.add(Dense(1, 'linear'))

opt = Adam(learning_rate=0.1)
cp = ModelCheckpoint('models/compl_ann.keras', save_best_only=True)
compl_ann.compile(optimizer=opt, loss='mse', metrics=[RootMeanSquaredError()])
compl_ann.fit(x=X_train_process, y=y_train, validation_data=(X_val_process, y_val), callbacks=[cp], epochs=10)

Epoch 1/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - loss: 246310731776.0000 - root_mean_squared_error: 496297.0312 - val_loss: 105770123264.0000 - val_root_mean_squared_error: 325223.1875
Epoch 2/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 240003579904.0000 - root_mean_squared_error: 489901.5938 - val_loss: 105540272128.0000 - val_root_mean_squared_error: 324869.6250
Epoch 3/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 236389548032.0000 - root_mean_squared_error: 486199.0938 - val_loss: 107412037632.0000 - val_root_mean_squared_error: 327737.7500
Epoch 4/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 232141832192.0000 - root_mean_squared_error: 481811.0000 - val_loss: 224208945152.0000 - val_root_mean_squared_error: 473507.0625
Epoch 5/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 21s 5ms/step - loss: 265462726656.0000 - root_mean_squared_error: 515230.7500 - val_loss: 92133842944.0000 - val_root_mean_squared_error: 303535.5625
Epoch 6/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 230968393728.0000 - root_mean_squared_error: 480591.7188 - val_loss: 94231560192.0000 - val_root_mean_squared_error: 306971.5938
Epoch 7/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 240543989760.0000 - root_mean_squared_error: 490452.8438 - val_loss: 83286786048.0000 - val_root_mean_squared_error: 288594.5000
Epoch 8/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - loss: 255861604352.0000 - root_mean_squared_error: 505827.6562 - val_loss: 85268570112.0000 - val_root_mean_squared_error: 292007.8125
Epoch 9/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 251014103040.0000 - root_mean_squared_error: 501013.0625 - val_loss: 218284081152.0000 - val_root_mean_squared_error: 467208.8125
Epoch 10/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 300837208064.0000 - root_mean_squared_error: 548486.3125 - val_loss: 133123194880.0000 - val_root_mean_squared_error: 364860.5000
Epoch 11/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 267258019840.0000 - root_mean_squared_error: 516970.0312 - val_loss: 131219357696.0000 - val_root_mean_squared_error: 362242.1250
Epoch 12/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - loss: 316012953600.0000 - root_mean_squared_error: 562150.3125 - val_loss: 214132178944.0000 - val_root_mean_squared_error: 462744.1875
Epoch 13/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - loss: 323560931328.0000 - root_mean_squared_error: 568824.1875 - val_loss: 214471639040.0000 - val_root_mean_squared_error: 463110.8125
Epoch 14/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - loss: 324391829504.0000 - root_mean_squared_error: 569554.0625 - val_loss: 210455642112.0000 - val_root_mean_squared_error: 458754.4375
Epoch 15/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 269644742656.0000 - root_mean_squared_error: 519273.2812 - val_loss: 77835460608.0000 - val_root_mean_squared_error: 278990.0625
Epoch 16/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 19s 4ms/step - loss: 277808447488.0000 - root_mean_squared_error: 527075.3750 - val_loss: 208639148032.0000 - val_root_mean_squared_error: 456770.3438
Epoch 17/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - loss: 327188971520.0000 - root_mean_squared_error: 572004.3750 - val_loss: 191948095488.0000 - val_root_mean_squared_error: 438118.8125
Epoch 18/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - loss: 243227918336.0000 - root_mean_squared_error: 493181.4375 - val_loss: 178981765120.0000 - val_root_mean_squared_error: 423062.3750
Epoch 19/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 19s 4ms/step - loss: 258399584256.0000 - root_mean_squared_error: 508330.1875 - val_loss: 89693306880.0000 - val_root_mean_squared_error: 299488.4062
Epoch 20/20
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - loss: 246841786368.0000 - root_mean_squared_error: 496831.7500 - val_loss: 92968853504.0000 - val_root_mean_squared_error: 304907.9375

In [37]:
from tensorflow.keras.models import load_model

compl_ann = load_model('models/compl_ann.keras')
mse(compl_ann.predict(X_train_process), y_train, squared=False), mse(simple_ann.predict(X_val_process), y_val, squared=False)

4376/4376 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step
228/228 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

(375283.65511219646, 470380.3219740291)

In [39]:
very_compl_ann = Sequential()
very_compl_ann.add(Input((11,))) # dataset has 11 features to input
very_compl_ann.add(Dense(256, 'relu'))
very_compl_ann.add(Dense(128, 'relu'))
very_compl_ann.add(Dense(64, 'relu'))
very_compl_ann.add(Dense(32, 'relu'))
very_compl_ann.add(Dense(1, 'linear'))

opt = Adam(learning_rate=0.1)
cp = ModelCheckpoint('models/very_compl_ann.keras', save_best_only=True)
very_compl_ann.compile(optimizer=opt, loss='mse', metrics=[RootMeanSquaredError()])
very_compl_ann.fit(x=X_train_process, y=y_train, validation_data=(X_val_process, y_val), callbacks=[cp], epochs=10)

Epoch 1/10
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 1606234275840.0000 - root_mean_squared_error: 1267373.0000 - val_loss: 169929146368.0000 - val_root_mean_squared_error: 412224.6250
Epoch 2/10
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - loss: 312880463872.0000 - root_mean_squared_error: 559357.1875 - val_loss: 169943990272.0000 - val_root_mean_squared_error: 412242.6250
Epoch 3/10
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 312926830592.0000 - root_mean_squared_error: 559398.6250 - val_loss: 169709355008.0000 - val_root_mean_squared_error: 411957.9375
Epoch 4/10
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 313263030272.0000 - root_mean_squared_error: 559699.0625 - val_loss: 169729556480.0000 - val_root_mean_squared_error: 411982.4688
Epoch 5/10
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 313525927936.0000 - root_mean_squared_error: 559933.8750 - val_loss: 170353442816.0000 - val_root_mean_squared_error: 412738.9375
Epoch 6/10
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 31s 7ms/step - loss: 313436143616.0000 - root_mean_squared_error: 559853.6875 - val_loss: 169728983040.0000 - val_root_mean_squared_error: 411981.7812
Epoch 7/10
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 313157648384.0000 - root_mean_squared_error: 559604.8750 - val_loss: 169957916672.0000 - val_root_mean_squared_error: 412259.5312
Epoch 8/10
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 24s 6ms/step - loss: 313293602816.0000 - root_mean_squared_error: 559726.3750 - val_loss: 169717989376.0000 - val_root_mean_squared_error: 411968.4375
Epoch 9/10
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - loss: 313266274304.0000 - root_mean_squared_error: 559701.9375 - val_loss: 170552590336.0000 - val_root_mean_squared_error: 412980.1250
Epoch 10/10
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 313269256192.0000 - root_mean_squared_error: 559704.6250 - val_loss: 169750167552.0000 - val_root_mean_squared_error: 412007.5000

In [41]:
from tensorflow.keras.models import load_model

very_compl_ann = load_model('models/very_compl_ann.keras')
mse(very_compl_ann.predict(X_train_process), y_train, squared=False), mse(simple_ann.predict(X_val_process), y_val, squared=False)

4376/4376 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

(559314.7757858858, 470380.3219740291)